name: budget_nerd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^7.3.3
  flutter_dotenv: ^5.0.2
  sentry_flutter: ^6.0.0
  provider: ^6.0.2 
  path_provider: ^2.0.9
  theme_provider: ^0.5.0
  moor: ^4.6.1
  moor_db_viewer: ^5.0.0
  sqlite3_flutter_libs:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  freezed: ^1.1.0 
  dartz: ^0.10.1
  equatable: ^2.0.3 
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3 
  dotted_border: ^2.0.0
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  math_expressions: ^2.3.0
  google_sign_in: ^5.2.4 
  flutter_slidable: ^1.2.0
  sticky_headers: ^0.2.0 
  carousel_slider: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1 
  moor_generator: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/utils/
    - assets/icons/
    - assets/icons/main/  


